name: Check Format Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort coverage
      - name: black
        run: |
          black --check gelidum
      - name: flake8
        run: |
          flake8 gelidum
      - name: isort
        run: |
          isort --check-only gelidum
